#define MAJOR 0
#define MINOR 0
#define PATCH 0
#define BUILD 1


// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR##.##MINOR##.##PATCH##.##BUILD

#define REQUIRED_VERSION 2.20
#define REQUIRED_CBA_VERSION {3,18,4}
#define REQUIRED_ACE_VERSION {3,20,0}