name: HEMTT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT check
      run: hemtt check
