name: Release Drafter

on:
  push:
    branches:
    - main
    - release-drafter  # for testing edits to this configuration

permissions:
  contents: read

jobs:
  draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}