name: Stringtables.xml

on:
  push:
    branches:
      - main

jobs:
  run_python:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      # Install Python packages
      - name: Install Python packages
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install pygithub

      # Checkout the repository
      - name: Checkout the source code
        uses: actions/checkout@v3

      # Pre-flight check for required secrets
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.TRANSLATION_ISSUE }}" ]; then
            echo "❌ TRANSLATION_ISSUE secret is not set."
            exit 1
          fi
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ GH_TOKEN secret is not set."
            exit 1
          fi
        shell: bash

      # Update Translation issue
      - name: Update Translation issue
        if: "! contains(github.event.head_commit.message, '[ci skip]')"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TRANSLATION_ISSUE: ${{ secrets.TRANSLATION_ISSUE }}
        run: python3 tools/stringtableDeploy.py
